import type { Metadata } from "next";
import Header from './Header/header';
import Footer from './Footer/footer';

export const metadata: Metadata = {
  title: "Sky Waves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/assets/logo.png" />
      </head>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
